CREATE TABLE IF NOT EXISTS Disciplinas(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text not null check (name <> ''),
    color text
);

CREATE TABLE IF NOT EXISTS Temas_estudio(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_disciplina INTEGER REFERENCES Disciplinas(id),
    nombre text not null check (name <> ''),
    color text,
    tag text
);

CREATE TABLE IF NOT EXISTS Tarjetas(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_tema_estudio INTEGER REFERENCES Temas_estudio(id),
    titulo text not null check (name <> ''),
    color text
);

CREATE TABLE IF NOT EXISTS Tar_contenidos(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_tarjeta INTEGER REFERENCES Tarjetas(id),
    contenido text not null check (name <> '')
);

CREATE TABLE IF NOT EXISTS Tar_ejemplos(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_tarjeta INTEGER REFERENCES Tarjetas(id),
    ejemplo text not null check (name <> '')
);